apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
  # annotations:
  #   service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
  #   service.beta.kubernetes.io/do-loadbalancer-algorithm: "least_connections"
spec:
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30009
  selector:
    app: api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-flask
        image: main_api:1.0
        ports: 
        - containerPort: 5000
      serviceAccountName: default
