
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-deployment
  labels:
    app: py
spec:
  replicas: 3
  selector:
    matchLabels:
      app: py
  template:
    metadata:
      labels:
        app: py
    spec:
      containers:
      - name: py
        image: main_api:1.0
